Override uId and gId for Tar in test
We can not use posix mode because of mTime can have nanoseconds

Test can fail on OS with user ID as long, eg:
java.lang.IllegalArgumentException: user id '604932503' is too big ( > 2097151 ).